name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
          
      - name: Install boost
        run: sudo apt-get install libboost-thread-dev
        
      - name: Run and collect coverage
        run: |
          coverage run --branch bmsStreaming.test.py
          coverage html
          
      - name: build for Receiver
        run: g++ -Wall -Wextra -o Receiver ./BMS_Reciever/BMS_Receiver.cpp ./BMS_Reciever/BMS_App.cpp    
        
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./htmlcov
          retention-days: 25
          
      - name: production code run
          run: python bmsStreaming.py | ./Receiver
